version: '3.8'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres-traineeApp'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: 'traineeApp'
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
