CREATE TABLE role_tbl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE task_tbl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    description VARCHAR(2048), 
    name VARCHAR(255), 
    PRIMARY KEY (id)
);

CREATE TABLE time_track_table (
    end_date TIMESTAMPTZ(6), 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    start_date TIMESTAMPTZ(6), 
    task_id BIGINT, 
    description VARCHAR(2048), 
    PRIMARY KEY (id)
);

CREATE TABLE user_role_tbl (
    role_id BIGINT NOT NULL, 
    user_id BIGINT NOT NULL
);

CREATE TABLE user_task_tbl (
    task_id BIGINT NOT NULL, 
    user_id BIGINT NOT NULL
);

CREATE TABLE user_tbl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    registration_time TIMESTAMPTZ(6), 
    email VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    password VARCHAR(255) NOT NULL, 
    phone_number VARCHAR(255) NOT NULL, 
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS time_track_table 
    ADD CONSTRAINT FKm632j74che8r08mv8nmlypqu3 
    FOREIGN KEY (task_id) 
    REFERENCES task_tbl(id);

ALTER TABLE IF EXISTS user_role_tbl 
    ADD CONSTRAINT FKpfkvhcexxtyx8f6mceq5sjds4 
    FOREIGN KEY (role_id) 
    REFERENCES role_tbl(id);

ALTER TABLE IF EXISTS user_role_tbl 
    ADD CONSTRAINT FK53b8oon0dkfbdetl5bsqfq0wn 
    FOREIGN KEY (user_id) 
    REFERENCES user_tbl(id);

ALTER TABLE IF EXISTS user_task_tbl 
    ADD CONSTRAINT FK3ixf8158slwt866um92fuwvq1 
    FOREIGN KEY (task_id) 
    REFERENCES task_tbl(id);

ALTER TABLE IF EXISTS user_task_tbl 
    ADD CONSTRAINT FK5ges0xguhajnq5hnxa5hlq77f 
    FOREIGN KEY (user_id) 
    REFERENCES user_tbl(id);
